### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by hibikikudo**
please update these packages. there are Regular Expression Denial of Service vulnerabilities https://nodesecurity.io/advisories/118

### CODE REVIEW

**Comment by oncletom** [comment]
@yaniswang would you like some help on this?

**Comment by ErikHellman** [comment]
This is a serious concern for me and probably the rest of the developer community that want to use htmlhint.

@yaniswang Any chance you could approve and merge this, and update the package on npm?

Thanks!

**Comment by thedaviddias** [comment]
Hey @ErikHellman, all packages will be soon updated and security checks will be done automatically and regularly.

**Comment by thedaviddias** [comment]
Solved by #251.

**Pull request closed without merging**
