### PR TITLE
Move jshint and csslint to optionalDependencies

### PR DESCRIPTION
**Pull request by Shinigami92**
**Fixes**: #174 

- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
_unit tests only fail if you use_ `npm install --no-optional`

#### Short description of what this resolves:

Not everyone uses csslint or jshint in their package.
If HTMLHint should use rules that use them, then it should be a dependency of the package that uses them.

#### Proposed changes:

- move jshint and csslint to `optinalDependencies`

### CODE REVIEW

**Comment by waldyrious** [comment]
@Shinigami92 with this merged, what would be the simplest way to install both dependencies? E.g. in [browserpad](https://github.com/browserpad/browserpad/blob/gh-pages/.travis.yml) I'm running simply:

    npm install htmlhint
    htmlhint --config htmlhint.conf index.xhtml

Where [htmlhint.conf](https://github.com/browserpad/browserpad/blob/gh-pages/htmlhint.conf) contains both `"jshint": {...}` and `"csslint": { ... }`.

I really would like a simple way to run htmlhint to check for any kind of html, css and js errors (similar to passing `-Wall` to a C++ compiler).

What would you suggest?

**Comment by Shinigami92** [comment]
@waldyrious `npm install htmlhint csslint jshint`

**Comment by waldyrious** [comment]
Fair enough. :+1:

**Comment by waldyrious** [comment]
@Shinigami92 is it expected that if I *don't* install csslint or jshint, but my config file *does* contain rules for them, htmlhint acts as if it did run the code through those linters and no errors were found? This is what I'm seeing with htmlhint 0.10.0.

I would expect htmlhint to warn me that those linters are not present (if I'm explicitly requesting them via the config file, of course), and therefore the "no errors" may not account for stuff they'd catch. Does that make sense? If so I'll open a new issue to track that.

**Comment by Shinigami92** [comment]
At first, if another dependency has JSHint or CSSLint as a dependency, the rules are active and working
The solution here would be to disable the rule or remove the rule from your .htmlhintrc
There is currenly no check implemented that warns the developer that the rule can not be used because the optional package is not installed
This can be an issue on its own indeed

**Comment by waldyrious** [comment]
> This can be an issue on its own indeed

Ok, I'll open one :+1:

**Pull request merged**
